name: webkeyz_task
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  # State management.
  flutter_bloc: ^8.1.2

  # Dependency injection
  get_it: ^7.2.0
  dartz: ^0.10.1

  # Network
  dio: ^5.0.2
  requests_inspector: ^2.5.0
  dio_cache_interceptor: ^3.4.0
  pretty_dio_logger: ^1.3.1

  # UI
  loading_animation_widget: ^1.2.0+4
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.1
  cupertino_icons: ^1.0.2
  animate_do: ^3.0.2

  # Local storage
  shared_preferences: ^2.0.18

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_gen:
  output: lib/shared/assets/
  line_length: 120

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
